### ISSUE TITLE
make install does not work

### ISSUE THREAD

**Issue by fdejax90** [Unstructured-IO/pipeline-sec-filings#182]
```bash
 make install
>>> 
python3 -m pip install pip==23.1.2
Requirement already satisfied: pip==23.1.2 in /Users/xxxx/.pyenv/versions/3.8.15/envs/sec-filings/lib/python3.8/site-packages (23.1.2)
WARNING: There was an error checking the latest version of pip.
pip install -r requirements/base.txt
Collecting anyio==3.7.0 (from -r requirements/base.txt (line 7))
  Using cached anyio-3.7.0-py3-none-any.whl (80 kB)
Collecting attrs==23.1.0 (from -r requirements/base.txt (line 11))
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting beautifulsoup4==4.12.2 (from -r requirements/base.txt (line 13))
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting bleach==6.0.0 (from -r requirements/base.txt (line 15))
  Using cached bleach-6.0.0-py3-none-any.whl (162 kB)
Collecting certifi==2023.5.7 (from -r requirements/base.txt (line 17))
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting charset-normalizer==3.1.0 (from -r requirements/base.txt (line 19))
  Using cached charset_normalizer-3.1.0-cp38-cp38-macosx_11_0_arm64.whl (121 kB)
Collecting click==8.1.3 (from -r requirements/base.txt (line 21))
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting defusedxml==0.7.1 (from -r requirements/base.txt (line 26))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting exceptiongroup==1.1.1 (from -r requirements/base.txt (line 28))
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting fastapi==0.95.2 (from -r requirements/base.txt (line 30))
  Using cached fastapi-0.95.2-py3-none-any.whl (56 kB)
Collecting fastjsonschema==2.17.1 (from -r requirements/base.txt (line 32))
  Using cached fastjsonschema-2.17.1-py3-none-any.whl (23 kB)
Collecting h11==0.14.0 (from -r requirements/base.txt (line 34))
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting httptools==0.5.0 (from -r requirements/base.txt (line 36))
  Using cached httptools-0.5.0-cp38-cp38-macosx_10_9_universal2.whl (230 kB)
Collecting idna==3.4 (from -r requirements/base.txt (line 38))
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting importlib-metadata==6.6.0 (from -r requirements/base.txt (line 42))
  Using cached importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Collecting importlib-resources==5.12.0 (from -r requirements/base.txt (line 46))
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting jinja2==3.1.2 (from -r requirements/base.txt (line 48))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting joblib==1.2.0 (from -r requirements/base.txt (line 52))
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting jsonschema==4.17.3 (from -r requirements/base.txt (line 56))
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting jupyter-client==8.2.0 (from -r requirements/base.txt (line 58))
  Using cached jupyter_client-8.2.0-py3-none-any.whl (103 kB)
Collecting jupyter-core==5.3.0 (from -r requirements/base.txt (line 60))
  Using cached jupyter_core-5.3.0-py3-none-any.whl (93 kB)
Collecting jupyterlab-pygments==0.2.2 (from -r requirements/base.txt (line 67))
  Using cached jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting lxml==4.9.2 (from -r requirements/base.txt (line 69))
  Using cached lxml-4.9.2.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... done
Collecting markupsafe==2.1.2 (from -r requirements/base.txt (line 71))
  Using cached MarkupSafe-2.1.2-cp38-cp38-macosx_10_9_universal2.whl (17 kB)
Collecting mistune==2.0.5 (from -r requirements/base.txt (line 75))
  Using cached mistune-2.0.5-py2.py3-none-any.whl (24 kB)
Collecting mypy==1.3.0 (from -r requirements/base.txt (line 77))
  Using cached mypy-1.3.0-cp38-cp38-macosx_11_0_arm64.whl (9.7 MB)
Collecting mypy-extensions==1.0.0 (from -r requirements/base.txt (line 79))
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting nbclient==0.8.0 (from -r requirements/base.txt (line 81))
  Using cached nbclient-0.8.0-py3-none-any.whl (73 kB)
Collecting nbconvert==7.4.0 (from -r requirements/base.txt (line 83))
  Using cached nbconvert-7.4.0-py3-none-any.whl (285 kB)
Collecting nbformat==5.9.0 (from -r requirements/base.txt (line 85))
  Using cached nbformat-5.9.0-py3-none-any.whl (77 kB)
Collecting nltk==3.8.1 (from -r requirements/base.txt (line 89))
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting numpy==1.24.3 (from -r requirements/base.txt (line 91))
  Using cached numpy-1.24.3-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
Collecting packaging==23.1 (from -r requirements/base.txt (line 96))
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pandocfilters==1.5.0 (from -r requirements/base.txt (line 100))
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting pkgutil-resolve-name==1.3.10 (from -r requirements/base.txt (line 102))
  Using cached pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting platformdirs==3.5.1 (from -r requirements/base.txt (line 104))
  Using cached platformdirs-3.5.1-py3-none-any.whl (15 kB)
Collecting pydantic==1.10.8 (from -r requirements/base.txt (line 106))
  Using cached pydantic-1.10.8-cp38-cp38-macosx_11_0_arm64.whl (2.5 MB)
Collecting pygments==2.15.1 (from -r requirements/base.txt (line 108))
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting pyrsistent==0.19.3 (from -r requirements/base.txt (line 110))
  Using cached pyrsistent-0.19.3-cp38-cp38-macosx_10_9_universal2.whl (82 kB)
Collecting python-dateutil==2.8.2 (from -r requirements/base.txt (line 112))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting python-dotenv==1.0.0 (from -r requirements/base.txt (line 114))
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting python-multipart==0.0.6 (from -r requirements/base.txt (line 116))
  Using cached python_multipart-0.0.6-py3-none-any.whl (45 kB)
Collecting pyyaml==6.0 (from -r requirements/base.txt (line 118))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/xxxx/.pyenv/versions/sec-filings/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/xxxx/.pyenv/versions/sec-filings/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/xxxx/.pyenv/versions/sec-filings/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/4r/qt2_c_d93gg36q06mpq5pm_00000gn/T/pip-build-env-yh9zc8j4/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
make: *** [install-base-pip-packages] Error 1

```

**Comment by fdejax90** [comment]
I solved the issue by doing:
```
pip install "cython<3.0.0" && pip install --no-build-isolation pyyaml==6.0
make install
```
